# Generated by Django 6.0.4 on 2026-05-08 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_chat_groupmember_group_members_message_privatechat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privatechat',
            name='chat',
        ),
    ]
