# Generated by Django 6.0.4 on 2026-05-08 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_privatechat_chat'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='privatechat',
            constraint=models.CheckConstraint(condition=models.Q(('user1_id__lt', models.F('user2_id'))), name='user1_less_than_user2'),
        ),
    ]
